name: Action release tagger
description: Automatically manage action releases
author: tj-actions
inputs:
  remote:
    description: 'Remote repository to push to'
    required: true
    default: 'origin'
outputs:
  major_version:
    description: The latest major version
    value: ${{ steps.release-tagger.outputs.major_version }}
  new_version:
    description: The new version
    value: ${{ steps.release-tagger.outputs.new_version }}

runs:
  using: 'composite'
  steps:
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: release-tagger
      shell: bash
      env:
        GITHUB_REF: ${{ github.ref }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        INPUTS_REMOTE: ${{ inputs.remote }}

branding:
  icon: tag
  color: white
